spring:
  application:
    name: activityservice
  data:
    mongodb:
      host: localhost
      port: 27017
      database: aiactivityfitness
server:
  port: 8082
logging:
  level:
    org.springframework.data.mongodb: DEBUG